<?php
//FOR MY PROJECT

//SQL credentials
define ("DB_HOST", "localhost");
define ("DB_USER", "hci573");
define ("DB_PASS", "hci573");
define ("DB_NAME", "hci573");

//tables
define ("TABLE_PRODUCTS", "products_chie");
define ("TABLE_INQUIRIES", "inquiries_chie");
define ("TABLE_USERS", "users_chie");

//connect to the SQL database
$link = mysql_connect(DB_HOST, DB_USER, DB_PASS) or die("Couldn't make connection.");
$db = mysql_select_db(DB_NAME, $link) or die("Couldn't select database");

/* a functions which return an array holding inquiries in the inquiry table */
function get_autocomplete_words(){

	//generate and execute the SQL query
	$query = "SELECT club, shaft, time FROM ".TABLE_INQUIRIES." ORDER BY RAND() LIMIT 4";
	$result = mysql_query($query) or die(mysql_error());

	while (true) {
	
		$row = mysql_fetch_array($result, MYSQL_BOTH);
		
		if (!$row)
			break;
			
		$words = array( 'club' => $row["club"], 'shaft' => $row["shaft"], 'time' => $row["time"] );
	
	}

/*	while ($row = mysql_fetch_array($result, MYSQL_BOTH)) {
		
		$words = array( 'club' => $row["club"], 'shaft' => $row["shaft"], 'time' => $row["time"] );

	}
*/	
	return $words;

/*	while ($row = mysql_fetch_array($result, MYSQL_BOTH)) {
		printf ("ID: %s  Name: %s  Time: %s", $row["club"], $row["shaft"], $row["time"]);
	}
	mysql_free_result($result);
*/

}

//function which returns submitted entry wrapped up in HTML code
/*function load_messages()
{
    //here, the variable $build holds the HTML content that is generated by the function
	$build = '';
	
	
	//setup our query and execute it
	$query = "SELECT * FROM ".TABLE_INQUIRIES." ORDER BY RAND() LIMIT 4";
    $msgq = mysql_query($query) or die(mysql_error());
    
	
	if(mysql_num_rows($msgq) == 0)
    {
       
		//the .= operator adds on to the current value of $build
		$build .= "<p><b>No data found.  Add some data using the form above</b></p>";
    }
    else
    {
        while($row = mysql_fetch_array($msgq))
        {
            $build .= "<div class=\"display\"><table style=\"width:100%;\"><td style=\"width:80%;\">";
			
			//generate the entry
            $build .= "<p><b>The Club:</b> ".$row['club']."<br />";
 
            $build .= "<b>The Shaft:</b> ".$row['shaft']."<br />";
 
            $build .= "<b>The Set:</b> ".$row['quantity']."<br />";
   
            $build .= "</div>";
        }
    }
    return $build;
}*/

?>